 name: VirtualAutoMiner
 version: 1.0.0
 author: Unknowncall
 
 main: net.pixelcade.virtualautominer.VirtualAutoMiner
 depend: [Vault, TokenEnchant]
 
 commands:
   automine:
     description: Main command for automine.
     aliases: [am]
 